### PR TITLE
New theme option

### PR DESCRIPTION
**Pull request by ibandim123**
Hi Payman! How are you?? Everything fine?

  I uped my modd in dev branch, i hope you response and i excited see him in action! I hope you a have good work week!

 Att, Isaac.

### CODE REVIEW

**Comment by peymanslh** [comment]
Hi Isaac!
Thanks for your PR. I'm checking it this week.

**Comment by ibandim123** [comment]
Ok, Payman! I wait eagerly, Thanks and good week!

**Comment by ibandim123** [comment]
Hi Payman, everything alright?

  Hi, i hope and wait your feedback about this dev branch.

**Comment by peymanslh** [comment]
Hi, 
Can you change it a little bit more?
For example, make the background darker, or use yellow instead of that pink color in the theme?

**Comment by ibandim123** [comment]
Hi, peymanslh

Ok, i make this more and i reply after finished for you see. Good Week✌



Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request closed without merging**
